#!/usr/bin/env sh
#
# Claude Code only: refuses hand-edits of generated artifacts. Why a hook and not
# `Edit(...)` denies (they also blocked the generators in the sandbox): hooks/AGENTS.md.

HOOK_LIB="${0%/*}/../lib"
[ -r "$HOOK_LIB/guard.sh" ] || {
  printf 'guard fault in %s: cannot read %s/guard.sh\n' "${0##*/}" "$HOOK_LIB" >&2
  exit 2
}
. "$HOOK_LIB/guard.sh"

FILE=$(field '.tool_input.file_path')
[ -n "$FILE" ] || emit_allow

case "/$FILE" in
  */.cloudflare/*)
    emit_deny "Blocked: $FILE is generated by cf (Build Output, Env types, local dev state). Change cloudflare.config.ts or the source, then run \`pnpm types\` or rebuild instead (see .claude/rules/core/guardrails.md)."
    ;;
  */routeTree.gen.ts)
    emit_deny "Blocked: $FILE is generated by the TanStack Router plugin. Change the route files and run \`pnpm --filter=<app> run routes:generate\` instead."
    ;;
  */CHANGELOG.md)
    emit_deny "Blocked: $FILE is written by \`changeset version\` in the Release workflow. Add or edit a pending .changeset/*.md instead (see .claude/rules/ops/changesets.md)."
    ;;
  */pnpm-lock.yaml)
    emit_deny "Blocked: $FILE is generated by pnpm. Change package.json or the pnpm-workspace.yaml catalog and run \`pnpm install\` instead."
    ;;
  */dist/* | */build/*)
    emit_deny "Blocked: $FILE is build output. Change the source and rebuild instead (see .claude/rules/core/guardrails.md)."
    ;;
esac

emit_allow
