#!/usr/bin/env sh
#
# Claude Code only: refuses hand-edits of generated artifacts. Why a hook and not
# `Edit(...)` denies (they also blocked the generators in the sandbox): hooks/AGENTS.md.

set -eu

emit_allow() {
  trap - EXIT INT TERM HUP
  exit 0
}

emit_deny() {
  trap - EXIT INT TERM HUP
  printf '%s\n' "$1" >&2
  exit 2
}

emit_fault() {
  trap - EXIT INT TERM HUP
  printf 'guard fault in %s: %s\n' "${0##*/}" "$1" >&2
  exit 2
}

trap 'emit_fault "unexpected error"' EXIT INT TERM HUP

INPUT=$(cat 2>/dev/null || true)
[ -n "$INPUT" ] || emit_allow

command -v jq >/dev/null 2>&1 || emit_fault "jq is required to parse the hook payload; install jq"

FILE=$(printf '%s' "$INPUT" | jq -r '.tool_input.file_path // empty' 2>/dev/null || true)
[ -n "$FILE" ] || emit_allow

case "/$FILE" in
  */worker-configuration.d.ts)
    emit_deny "Blocked: $FILE is generated by \`wrangler types\`. Change wrangler.jsonc and run \`pnpm types\` instead (see .claude/rules/core/guardrails.md)."
    ;;
  */routeTree.gen.ts)
    emit_deny "Blocked: $FILE is generated by the TanStack Router plugin. Change the route files and run \`pnpm --filter=<app> run routes:generate\` instead."
    ;;
  */dist/* | */build/*)
    emit_deny "Blocked: $FILE is build output. Change the source and rebuild instead (see .claude/rules/core/guardrails.md)."
    ;;
esac

emit_allow
